name: Build API Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'services/api/**'
      - 'docker-compose.yml'
      - '.github/workflows/docker-api.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'services/api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API image
        uses: docker/build-push-action@v6
        with:
          context: ./services/api
          push: false
          tags: api:ci

