name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r services/api/requirements.txt
          pip install -r requirements-dev.txt

      - name: Black (check)
        run: black --check .

      - name: isort (check)
        run: isort --check-only .

      - name: Flake8
        run: flake8 .

      - name: Pytest
        run: pytest -q

